openapi: "3.0.3"
info:
  title: "matrikkel_bygning_egenregistering API"
  description: "matrikkel_bygning_egenregistering API"
  version: "1.0.0"
servers:
- url: "https://matrikkel_bygning_egenregistering"
paths:
  /metrics:
    get:
      description: ""
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                type: "string"
  /v1/bygning:
    get:
      description: ""
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/Bygning"
    post:
      description: ""
      requestBody:
        content:
          '*/*':
            schema:
              $ref: "#/components/schemas/Bygning"
        required: true
      responses:
        "201":
          description: "Created"
          content:
            '*/*':
              schema:
                type: "string"
        "500":
          description: "Internal Server Error"
          content:
            '*/*':
              schema:
                type: "object"
components:
  schemas:
    Bygning:
      type: "object"
      properties:
        id:
          type: "string"
        byggeaar:
          type: "integer"
          format: "int32"
        areal:
          type: "number"
          format: "double"
        energikilder:
          type: "array"
          items:
            type: "string"
            enum:
            - "NOE"
            - "NOE_ANNET"
        oppvarming:
          type: "array"
          items:
            type: "string"
            enum:
            - "VARMEPUMPE"
        vann:
          type: "boolean"
        avlop:
          type: "boolean"