name: Build and Push Image to Registry
on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write
  packages: write

env:
  registry: ghcr.io
  image_name: ${{ github.repository }}

jobs:
  build:
    name: Docker build and push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout project sources
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Build with Gradle
        run: ./gradlew build

      - name: Login to Github Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.registry }}
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Build docker and push
        id: build
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.registry }}/${{ github.repository }}:latest